# -*- coding: utf-8 -*-
"""GB-Exno3-Appds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0vEaPos-rLfeC4y_xXMFLA8tpFtK7zg
"""

import pandas as pd
import numpy as np

pip install pandas numpy scikit-learn fuzzywuzzy python-Levenshtein

from fuzzywuzzy import process
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('')

df.head()

dx = pd.read_csv('')



# CHECK THE DIMENSIONALITY OF THE DATA OF df & dx

# REMOVE THE DUPLICATES DATA OF df & dx

# Standardize column names for merging
 ['Product_id','Product_Name','Rating', 'Review_Count']

['Product_id','Product_Name','Rating', 'Review_Count']



dx['Matched_Product'] =

merged_df =

merged_df

merged_df.columns

merged_df['Combined_Rating'] =

#CALCULATE merged_df['Recommendation_Score'] 0.7 -> merged_df['Combined_Rating']  0.3-> merged_df['Rating_ds1']

merged_df.head()

# sort the values by Recommendation_Score

# print the best_products and store it as a CSV file

rp=pd.read_csv('')

rp.head()